### ISSUE TITLE
ntlm-auth is deprecated

### ISSUE THREAD

**Issue by Arkelis** [ulodciv/httpx-ntlm#4]
[`ntlm-auth`](https://github.com/jborean93/ntlm-auth) is deprecated, the maintainer recommends using [`pyspnego`](https://github.com/jborean93/pyspnego)

**Comment by caspervk** [comment]
I have a fork and preliminary MR fixing this issue here: https://github.com/ulodciv/httpx-ntlm/pull/7 / https://github.com/magenta-aps/httpx-ntlm.

**Comment by caspervk** [comment]
The MR has been merged. Thanks @ulodciv
