### ISSUE TITLE
Support for later cryptography

### ISSUE THREAD

**Issue by fabaff** [ulodciv/httpx-ntlm#6]
[`cryptography`](https://github.com/pyca/cryptography) is released on a regular base. The current [constraint](https://github.com/ulodciv/httpx-ntlm/blob/master/requirements.txt#L3) doesn't allow to use later releases.

This is an issue for distribution which are shipping `httpx-ntlm` as package and users who are using a `venv`.

**Comment by ulodciv** [comment]
The requirement has been updated, thanks @caspervk
